export const NATION_CODES = {
  Portugal: "POR",
  Brazil: "BRA",
  Netherlands: "NED",
  England: "ENG",
  Argentina: "ARG",
  Morocco: "MAR",
  France: "FRA",
  "Ivory Coast": "CIV",
  Uruguay: "URU",
  Turkey: "TUR",
  Belgium: "BEL",
};

export const PLAYERS = [
  { id: "bruno", name: "Bruno Fernandes", nation: "Portugal", wiki: "Bruno_Fernandes",
    position: "Attacking midfielder", role: "Manchester United captain and creative talisman",
    bio: [
      "United's captain since 2023 and the team's heartbeat; joined from Sporting CP in January 2020.",
      "Broke the Premier League single-season assist record (21) in 2025–26 and won both the FWA and Premier League Player of the Season.",
      "Elite penalty taker and set-piece deliverer with a habit of scoring spectacular long-range goals.",
      "A Portugal mainstay with 80+ caps, long playing alongside Cristiano Ronaldo.",
      "Style: relentless energy, vision and visible leadership — when he plays well, United usually do.",
    ] },
  { id: "dalot", name: "Diogo Dalot", nation: "Portugal", wiki: "Diogo_Dalot",
    position: "Full-back", role: "First-choice right-back, can fill in at left-back",
    bio: [
      "Versatile full-back comfortable on either flank; United's regular right-back.",
      "A Porto academy product who joined United in 2018.",
      "Tireless up and down the touchline with much-improved defending.",
      "An established Portugal international valued for stamina and tactical flexibility.",
      "Style: attacking, high-energy, dependable two-way output.",
    ] },
  { id: "casemiro", name: "Casemiro", nation: "Brazil", wiki: "Casemiro",
    position: "Defensive midfielder", role: "United's midfield anchor and enforcer",
    bio: [
      "Holding midfielder who shields the back line; joined United from Real Madrid in 2022.",
      "Five-time Champions League winner — one of the most decorated midfielders of his era.",
      "Surprisingly prolific in 2025–26, scoring nine league goals from deep.",
      "Hugely experienced Brazil international and on-field leader.",
      "Style: positional discipline, ferocious tackling, late runs — but picks up plenty of cards.",
    ] },
  { id: "cunha", name: "Matheus Cunha", nation: "Brazil", wiki: "Matheus_Cunha",
    position: "Forward / attacking midfielder", role: "Club-record-fee signing, creative front-man",
    bio: [
      "Versatile forward who can play as a 9, a 10 or off the left; a £62.5m signing from Wolves in 2025.",
      "One of United's top scorers in 2025–26 (10 league goals) in his debut season.",
      "An Olympic gold medallist with Brazil at the Tokyo 2020 Games.",
      "Brings flair, fight and fan-favourite energy.",
      "Style: creative, press-resistant and combative in tight spaces.",
    ] },
  { id: "deligt", name: "Matthijs de Ligt", nation: "Netherlands", wiki: "Matthijs_de_Ligt",
    position: "Centre-back", role: "Senior central defender and organiser",
    bio: [
      "Commanding centre-back who joined United from Bayern Munich in 2024.",
      "Former Ajax captain who reached a Champions League semi-final as a teenager and won the 2018 Golden Boy award.",
      "Scored a dramatic stoppage-time equaliser at Tottenham in November 2025.",
      "A long-serving Netherlands international and natural leader.",
      "Style: aggressive front-foot defending, strong in the air, composed in possession.",
    ] },
  { id: "zirkzee", name: "Joshua Zirkzee", nation: "Netherlands", wiki: "Joshua_Zirkzee",
    position: "Forward", role: "Rotation centre-forward / link striker",
    bio: [
      "Technical centre-forward and squad option, signed from Bologna in 2024.",
      "Developed at Bayern Munich before breaking out in Serie A.",
      "Chipped in important goals from the bench in 2025–26.",
      "Capped by the Netherlands, though his World Cup squad place is not guaranteed.",
      "Style: hold-up play, a soft first touch and clever combination football.",
    ] },
  { id: "maguire", name: "Harry Maguire", nation: "England", wiki: "Harry_Maguire",
    position: "Centre-back", role: "Experienced defender and former captain",
    bio: [
      "Experienced central defender and a former United captain.",
      "Signed for £80m in 2019 — once the world's most expensive defender.",
      "Reinvented himself as a dependable leader; scored the winner at Liverpool in October 2025.",
      "An England regular since the 2018 World Cup with a strong tournament record.",
      "Style: aerial dominance at both ends, a set-piece threat, and an occasional emergency striker.",
    ] },
  { id: "shaw", name: "Luke Shaw", nation: "England", wiki: "Luke_Shaw",
    position: "Left-back / centre-back", role: "First-choice left-sided defender",
    bio: [
      "Left-sided defender who was ever-present across the 2025–26 league season.",
      "Joined United from Southampton back in 2014.",
      "Scored in the Euro 2020 final — the fastest goal in a European Championship final.",
      "Battled back from years of injuries to reclaim a key role for club and country.",
      "Style: overlapping runs, a quality left foot and the ability to cover centre-back.",
    ] },
  { id: "mainoo", name: "Kobbie Mainoo", nation: "England", wiki: "Kobbie_Mainoo",
    position: "Central midfielder", role: "Academy graduate, ball-progressing midfielder",
    bio: [
      "Composed central midfielder and a homegrown academy graduate.",
      "Burst onto the scene in 2023–24 and scored in the FA Cup final win over Manchester City.",
      "Found the net against Liverpool in May 2026.",
      "A young England international tipped for a long career at the top.",
      "Style: calm under pressure, smart ball progression and maturity beyond his years.",
    ] },
  { id: "mount", name: "Mason Mount", nation: "England", wiki: "Mason_Mount",
    position: "Attacking midfielder", role: "Versatile midfielder / forward",
    bio: [
      "Versatile attacking midfielder who joined from Chelsea in 2023.",
      "Two-time Chelsea Player of the Year and a 2021 Champions League winner.",
      "After an injury-disrupted spell, contributed goals in 2025–26 (Sunderland, Crystal Palace, Wolves).",
      "An England international from the Southgate era.",
      "Style: tireless pressing, late runs and two-footed finishing — fitness is key to his involvement.",
    ] },
  { id: "licha", name: "Lisandro Martínez", nation: "Argentina", wiki: "Lisandro_Martínez",
    position: "Centre-back", role: "Combative ball-playing defender",
    bio: [
      "Aggressive left-footed centre-back nicknamed 'The Butcher' (El Carnicero).",
      "Joined United from Ajax in 2022.",
      "A 2022 World Cup winner with Argentina.",
      "Returned from a long knee injury during the 2025–26 season.",
      "Style: ferocious in duels and excellent on the ball despite a smaller frame for a defender.",
    ] },
  { id: "mazraoui", name: "Noussair Mazraoui", nation: "Morocco", wiki: "Noussair_Mazraoui",
    position: "Full-back", role: "Versatile defender across the back line",
    bio: [
      "Versatile right-back who can also play left-back or in midfield; signed from Bayern in 2024.",
      "A key figure in Morocco's historic run to the 2022 World Cup semi-finals.",
      "An Ajax academy product with Champions League pedigree.",
      "Reliable two-way full-back for club and country.",
      "Style: tidy in possession, tactically intelligent and defensively solid.",
    ] },
  { id: "yoro", name: "Leny Yoro", nation: "France", wiki: "Leny_Yoro",
    position: "Centre-back", role: "Highly-rated young central defender",
    bio: [
      "Young centre-back signed from Lille in 2024 as one of Europe's brightest prospects.",
      "Overcame an early foot injury to establish himself in the side in 2025–26.",
      "A France youth standout now pushing into the senior set-up.",
      "Style: pace, sharp recovery defending, composure and aerial ability — a very high ceiling.",
    ] },
  { id: "amad", name: "Amad Diallo", nation: "Ivory Coast", wiki: "Amad_Diallo",
    position: "Winger / wing-back", role: "Direct, creative wide attacker",
    bio: [
      "Right winger or attacking wing-back who joined from Atalanta in 2021.",
      "Scored a dramatic late FA Cup winner in the Manchester derby — an instant fan favourite.",
      "An Ivory Coast international full of flair and unpredictability.",
      "Productive in 2025–26 with goals against Nottingham Forest and Bournemouth.",
      "Style: low centre of gravity, fearless dribbling and creativity in tight areas.",
    ] },
  { id: "ugarte", name: "Manuel Ugarte", nation: "Uruguay", wiki: "Manuel_Ugarte",
    position: "Defensive midfielder", role: "Ball-winning holding midfielder",
    bio: [
      "Holding midfielder who joined from Paris Saint-Germain in 2024.",
      "A Uruguay international known for aggressive ball-winning.",
      "Developed at Sporting CP before his move to PSG.",
      "Provides bite, energy and defensive cover in midfield.",
      "Style: tackles, interceptions and high pressing — a classic destroyer at the base of midfield.",
    ] },
  { id: "bayindir", name: "Altay Bayındır", nation: "Turkey", wiki: "Altay_Bayındır",
    position: "Goalkeeper", role: "Squad goalkeeper",
    bio: [
      "Goalkeeper who pushed for United's number one shirt before Senne Lammens' arrival.",
      "Signed from Fenerbahçe in 2023.",
      "An experienced Turkey international keeper.",
      "Style: a strong shot-stopper who is comfortable with the ball at his feet.",
      "Likely a backup option for Turkey at the tournament.",
    ] },
  { id: "lammens", name: "Senne Lammens", nation: "Belgium", wiki: "Senne_Lammens",
    position: "Goalkeeper", role: "First-choice goalkeeper",
    bio: [
      "Goalkeeper who became United's first choice during 2025–26 after a move from Royal Antwerp.",
      "A young Belgian shot-stopper who settled quickly at Old Trafford.",
      "Tall and commanding in his box.",
      "Style: sharp reflexes and modern, ball-playing distribution.",
      "An emerging option in the Belgium goalkeeping pool.",
    ] },
];
